spring.application.name=Enterprise-Warehouse-Management-System

spring.datasource.url=jdbc:postgresql://localhost:5432/EWMS_DB
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

server.port=8080